/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Daniel Teixeira
 */
public class Janela extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public Janela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        valor1 = new javax.swing.JTextField();
        opcoes = new javax.swing.JComboBox < > ();
        saida = new javax.swing.JTextField();
        imagem = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        valor2 = new javax.swing.JTextField();
        enter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aritmética Binária");
        setResizable(false);

        opcoes.setModel(new javax.swing.DefaultComboBoxModel < > (new String[] {
            "+",
            "-"
        }));

        saida.setEditable(false);
        saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaActionPerformed(evt);
            }
        });

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.png"))); // NOI18N

        enter.setText("=");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saida, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(valor1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(valor2)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(enter))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(imagem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(valor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(enter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    } // </editor-fold>                        

    private void saidaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {
        if (this.opcoes.getSelectedIndex() == 0) { //SOMA
            String primeiro = valor1.getText();
            String segundo = valor2.getText();
            String saida = "";

            int comp1 = primeiro.length() - 1;
            int comp2 = segundo.length() - 1;
            if (comp1 != comp2) {
                int acres = 0;
                if (comp1 > comp2) {
                    acres = comp1 - comp2;
                    for (int j = 0; j < acres; j++) {
                        segundo = '0' + segundo;
                    }
                } else if (comp1 < comp2) {
                    acres = comp2 - comp1;
                    for (int j = 0; j < acres; j++) {
                        primeiro = '0' + primeiro;
                    }
                }
            }

            comp1 = primeiro.length() - 1;
            comp2 = segundo.length() - 1;
            
            System.out.println(primeiro);
            System.out.println(segundo);
            int sobe = 0;

            for (int i = comp1; i >= 0; i--) {
                System.out.println("primeiro na posicao " + i + " " + primeiro.charAt(i));
                System.out.println("segundo na posicao " + i + " " + segundo.charAt(i));
                System.out.println("sobe " + sobe);
                if (sobe == 1) {
                    if (i == 0) {
                        if ((primeiro.charAt(i) == '1') && (segundo.charAt(i) == '1')) {
                            saida = "11" + saida;
                        } else if ((primeiro.charAt(i) == '1') && (segundo.charAt(i) == '0')) {
                            saida = "10" + saida;
                        } else if ((primeiro.charAt(i) == '0') && (segundo.charAt(i) == '1')) {
                            saida = "10" + saida;
                        } else if ((primeiro.charAt(i) == '0') && (segundo.charAt(i) == '0')) {
                            saida = '1' + saida;
                        }
                    } else {
                        if ((primeiro.charAt(i) == '1') && (segundo.charAt(i) == '1')) {
                            saida = '1' + saida;
                            sobe = 1;
                            continue;
                        } else if ((primeiro.charAt(i) == '1') && (segundo.charAt(i) == '0')) {
                            saida = '0' + saida;
                            sobe = 1;
                            continue;
                        } else if ((primeiro.charAt(i) == '0') && (segundo.charAt(i) == '1')) {
                            saida = '0' + saida;
                            sobe = 1;
                            continue;
                        } else if ((primeiro.charAt(i) == '0') && (segundo.charAt(i) == '0')) {
                            saida = '1' + saida;
                        }
                    }
                    sobe = 0;
                } else {
                    if ((primeiro.charAt(i) == '1') && (segundo.charAt(i) == '1')) {
                        if (i == 0) {
                            saida = "10" + saida;
                        } else {
                            saida = '0' + saida;
                        }
                        sobe = 1;
                    } else if ((primeiro.charAt(i) == '1') && (segundo.charAt(i) == '0')) {
                        saida = '1' + saida;
                    } else if ((primeiro.charAt(i) == '0') && (segundo.charAt(i) == '1')) {
                        saida = '1' + saida;
                    } else if ((primeiro.charAt(i) == '0') && (segundo.charAt(i) == '0')) {
                        saida = '0' + saida;
                    }
                }
            }
            
            this.saida.setText(saida);
        } else { //SUBTRAÇÃO
            System.out.println("SUBTRAÇÃO");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info: javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Janela dialog = new Janela(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton enter;
    private javax.swing.JLabel imagem;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox < String > opcoes;
    private javax.swing.JTextField saida;
    private javax.swing.JTextField valor1;
    private javax.swing.JTextField valor2;
    // End of variables declaration                   
}